language: php

php:
    - 7.3
    - 7.4

jdk:
    # Needed for local Neo4j 2.0+
    - oraclejdk8

before_install:
    - composer install --prefer-source --no-interaction

install:
    - wget http://dist.neo4j.org/neo4j-enterprise-3.5.16-unix.tar.gz
    - mkdir neo
    - tar xzf neo4j-enterprise-3.5.16-unix.tar.gz -C neo --strip-components=1
    - sed -i.bak '0,/\(dbms\.security\.auth_enabled=\).*/s/^#//g' ./neo/conf/neo4j.conf
    - cat ./neo/conf/neo4j.conf
    - neo/bin/neo4j start &
    - sleep 10 # do not remove this line !

script:
    - vendor/bin/phpunit --exclude-group fail
    - vendor/bin/behat

notifications:
    email: "alexandre.tranchant@gmail.com"
